"""Sample customer wording per theme. {p} is replaced with a product name."""
V = {
"EFF-01":["Sorry but this just does nothing. Used {p} for three weeks and no difference at all.",
          "Completely ineffective for me. Wish I'd bought something else."],
"EFF-02":["It's fine, just not the miracle the website promises. Expected more for the money.",
          "Does the job but nothing special. A bit underwhelmed by {p}."],
"EFF-03":["I've used {p} for over a year and this batch just isn't the same. Doesn't work like it used to.",
          "Something has changed. My last bottle was great, this one does nothing."],
"EFF-04":["Turns out this isn't right for oily skin. Wish the description had been clearer.",
          "Bought the wrong one for my skin type - my fault but the site wasn't much help."],
"EFF-05":["This has left yellow marks on my white pillowcases. Really annoyed.",
          "Stained my t-shirt. Won't be repurchasing."],
"EFF-06":["Leaves a horrible film on my skin no matter how long I rinse.",
          "Feels like it never fully washes off."],
"EFF-07":["Barely lasted three weeks. My previous one lasted two months easily.",
          "Gone through {p} far quicker than usual - is there less in there?"],
"RXN-01":["Came out in a red itchy rash within a day of using {p}. Had to stop.",
          "Burning sensation almost immediately. Skin was red for two days."],
"RXN-02":["Broke out in spots along my jaw after a week. Never had that before.",
          "Caused a really bad breakout. Gutted, I wanted to love this."],
"RXN-03":["This contains a nut derivative and I'm allergic - it isn't obvious on the front.",
          "Reacted badly, then realised it has an ingredient I know I can't use."],
"RXN-04":["I had no idea there was fragrance in the 'sensitive' one. Please make this clearer.",
          "The ingredients list is tiny and I couldn't read it before buying."],
"RXN-05":["Ended up at the walk-in centre with a swollen face. I'd like someone to call me.",
          "Had to get medical advice after using this. Please take this seriously."],
"RXN-06":["Got some in my eye and it stung badly for an hour.",
          "My toddler got hold of it and put some in her mouth - is it safe?"],
"RXN-07":["Used this on my son and his skin came up in a rash straight away.",
          "Would not recommend for children, my daughter reacted badly."],
"SEN-01":["The scent is completely overpowering. Can smell it across the room.",
          "Far too strong for me, gave me a headache."],
"SEN-02":["Lovely when you first use it but the scent vanishes in minutes.",
          "Can barely smell anything at all. Disappointing."],
"SEN-03":["This doesn't smell like it used to. Have you changed the formula?",
          "The scent is different from my last one and not in a good way."],
"SEN-04":["Something about the smell is off. Not pleasant.",
          "Has a slightly chemical smell I really don't like."],
"SEN-05":["Texture is gritty and it's separated in the bottle. Doesn't look right.",
          "Lumpy and watery at the same time. Something's wrong with this one."],
"SEN-06":["Much runnier than the last one I had. Pours straight out.",
          "Far too thick now, hard to get out of the bottle."],
"SEN-07":["The colour is a strange yellow, my old one was white.",
          "Looks discoloured compared to the previous bottle."],
"SEN-08":["Just not my kind of scent, personal preference really.",
          "Not keen on the fragrance but the product itself is fine."],
"DES-01":["The pump has completely seized after about six weeks. Can't get anything out.",
          "Pump stopped working on {p}. Had to unscrew the top and pour it."],
"DES-02":["Pump gives out about three times more than you need every press.",
          "Barely dispenses anything, you have to press it five times."],
"DES-03":["The bottle is enormous, doesn't fit on my shelf at all.",
          "Too bulky and awkward to hold with wet hands."],
"DES-04":["It won't stand up properly, falls over constantly.",
          "Base is too narrow, it topples every time."],
"DES-05":["Refilling is a nightmare. Ended up with half the pouch on the floor.",
          "The pouch is really hard to open and then it glugs everywhere."],
"DES-06":["The cap doesn't screw on properly any more, it leaks.",
          "Closure doesn't seal - found it leaking in my bag."],
"DES-07":["Feels quite cheap and plasticky for the price.",
          "Packaging doesn't match the premium price point."],
"DES-08":["The writing on the label is far too small to read.",
          "Can't tell which variant is which, the labels look identical."],
"DES-09":["Loads of unnecessary packaging for a refill brand. Bit ironic.",
          "The outer wrap isn't recyclable which seems odd for you."],
"CON-01":["Arrived completely leaked. The box was soaked and half the pouch was empty.",
          "Second delivery in a row where {p} has leaked everywhere in transit."],
"CON-02":["Bottle arrived cracked and product all over the packaging.",
          "Turned up smashed. Not well packed at all."],
"CON-03":["This has clearly been opened and used. Seal was already broken.",
          "Received what looks like a returned item - it's been used."],
"CON-04":["No seal on it at all when it arrived. Didn't feel safe using it.",
          "The safety seal was already broken."],
"CON-05":["The bottle was only about two thirds full when it arrived.",
          "Definitely less product in here than it says on the label."],
"CON-06":["Best before date is next month. That's not much use for a subscription.",
          "Arrived already out of date."],
"CON-07":["Outer box was battered but the product inside was thankfully fine.",
          "Packaging arrived crushed, contents okay."],
"DEL-01":["My order still hasn't arrived, it's been eleven days now.",
          "No sign of my delivery and no update from the courier."],
"DEL-02":["Order is over a week late with no explanation.",
          "Still waiting. Was meant to be here Tuesday."],
"DEL-03":["Courier has confirmed the parcel is lost. What happens now?",
          "Tracking says lost in transit. Nobody has contacted me."],
"DEL-04":["Two items missing from my order - the cleanser and the lip balm.",
          "Only half my order turned up."],
"DEL-05":["Sent me the wrong scent entirely. Ordered Sea Salt, got Fig.",
          "Received someone else's order by the look of it."],
"DEL-06":["Delivered to a completely different address on the next street.",
          "Left at a neighbour I've never heard of."],
"DEL-07":["Marked as delivered but nothing has arrived. No card, nothing.",
          "Tracking says delivered and signed for. It wasn't."],
"DEL-08":["Courier didn't knock and left no card, just marked me as out.",
          "Driver never even attempted delivery."],
"DEL-09":["Tracking hasn't updated in five days. Is it still coming?",
          "No tracking movement since it left the warehouse."],
"SUB-01":["I'd like to cancel my subscription please.",
          "Please cancel - I've got too much stock built up."],
"SUB-02":["Can I skip next month's delivery? Still got plenty.",
          "Please push my next order back by four weeks."],
"SUB-03":["Want to swap the Fig for the Unscented on my subscription.",
          "Can I change to every 12 weeks instead of 8?"],
"SUB-04":["I didn't realise this was a subscription - I thought it was a one-off.",
          "Been charged again and I never signed up for recurring orders."],
"SUB-05":["I've been charged £34 but my subscription is £24.60.",
          "The amount taken doesn't match what my account says."],
"SUB-06":["Charged twice for the same order this month.",
          "Two identical payments have come out."],
"SUB-07":["My payment failed but my card is fine. Can you retry?",
          "Getting a payment error every time I try to update my card."],
"SUB-08":["These are arriving far too often, I've got six unopened.",
          "Every 4 weeks is way too much, I can't use it that fast."],
"SUB-09":["My 20% code didn't apply at checkout.",
          "Discount wasn't taken off even though it said applied."],
"SUB-10":["I can't find anywhere on the site to manage my subscription.",
          "There's no obvious way to pause. Had to email instead."],
"RFD-01":["Returned this three weeks ago and still no refund.",
          "No refund received despite confirmation you'd had it back."],
"RFD-02":["Refund is taking much longer than the 5 days you promised.",
          "Still waiting on my money after two weeks."],
"RFD-03":["Refunded the wrong amount - short by the delivery charge.",
          "Only got part of my money back."],
"RFD-04":["How do I return this? Can't find the instructions.",
          "What's the returns process please?"],
"RFD-05":["The returns label link doesn't work.",
          "Can't download my return label, keeps erroring."],
"RFD-06":["Told me I can't return it because it's opened. How else would I know it caused a rash?",
          "Refused my refund on a faulty item. Not good enough."],
"AVL-01":["The Sea Salt refill has been out of stock for a month.",
          "Everything I want is unavailable."],
"AVL-02":["Bought the bottle in Halden's and now they don't stock the refills anywhere.",
          "Can't find refills in any shop near me. Defeats the point."],
"AVL-03":["Gutted you've discontinued my favourite scent.",
          "Why has the Bergamot been removed?"],
"AVL-04":["Where can I buy this in person?",
          "Do you have any stockists in Scotland?"],
"AVL-05":["It's £3 cheaper on the marketplace than on your own site.",
          "Why is it a different price in store?"],
"AVL-06":["You don't ship to Ireland which is frustrating.",
          "No delivery option for my country."],
"SVC-01":["Emailed twice last week and heard nothing back.",
          "Third time chasing this now."],
"SVC-02":["Took four days to get a reply.",
          "Response times are very slow."],
"SVC-03":["The reply I got was quite curt and unhelpful.",
          "Felt fobbed off, to be honest."],
"SVC-04":["I've explained this to three different people now.",
          "Had to repeat the whole story again."],
"SVC-05":["This still isn't sorted after a month of emails.",
          "Original problem is still not resolved."],
"VAL-01":["£11 for that little? Doesn't feel like value.",
          "Not much product in there for the price."],
"VAL-02":["Nice enough but far too expensive for what it is.",
          "Overpriced compared to what's in Boots."],
"VAL-03":["The refill is only £2 cheaper than a new bottle. What's the incentive?",
          "Refills should be much cheaper than they are."],
"VAL-04":["£4.95 delivery on a £9 refill is steep.",
          "Delivery costs more than the product almost."],
"VAL-05":["Another price rise. That's twice this year.",
          "Prices have gone up again and I'm reconsidering."],
"PRA-01":["Absolutely love {p}, been using it for two years now.",
          "Best product I've bought all year. Genuinely brilliant."],
"PRA-02":["The Fig scent is gorgeous, get compliments constantly.",
          "Smells incredible. Could not be happier."],
"PRA-03":["First thing that hasn't irritated my skin in years. Thank you.",
          "Finally something my sensitive skin gets on with."],
"PRA-04":["Sophie in your team sorted my problem in minutes. Brilliant service.",
          "Really impressed with how quickly you dealt with my issue."],
"PRA-05":["Love that I'm not throwing away a bottle every month.",
          "Packaging is beautiful and the refill system actually works."],
"PRA-06":["Ordered Monday, arrived Tuesday. Excellent.",
          "Fastest delivery I've had from anyone."],
}
